name: Build and Deploy Application

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy-flask:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Log in to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t statementsmart:latest ./app

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "statementsmart:latest"
          format: "table"
          exit-code: "0" # Set to "1" to fail on findings
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Tag image for ACR
        run: docker tag statementsmart:latest ${{ secrets.ACR_LOGIN_SERVER }}/statementsmart:latest

      - name: Push Docker image to ACR
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/statementsmart:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/statementsmart:latest
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP }}
          containerAppName: statementsmart
